apiVersion: apps/v1
kind: Deployment
metadata:
    name: wo-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            wo-ptr: wo-ptr
    template:
        metadata:
            labels:
                wo-ptr: wo-ptr
        spec:
            containers:
                - name: wo-con
                  image: wordpress
                  imagePullPolicy: Never
                  ports:
                  - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
    annotations:
        metallb.universe.tf/allow-shared-ip: shared
    name: wordpress-svc
spec:
    type: LoadBalancer
    selector:
        wo-ptr: wo-ptr
    ports:
        - port: 100
          targetPort: 5050
