apiVersion: apps/v1
kind: Deployment
metadata:
    name: influx-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            inf-ptr: inf-ptr
    template:
        metadata:
            labels:
                inf-ptr: inf-ptr
        spec:
            containers:
                - name: inf-con
                  image: influxdb
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
    name: influxdb-svc
spec:
    selector:
        inf-ptr: inf-ptr
    ports:
      - port: 8086
        targetPort: 8086
